# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
      - python-enchant
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  # force pyang version with patches
  - pip install -I git+https://github.com/abravalheri/pyang.git@deploy
  - pip install pyenchant
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
