# -*- coding: utf-8 -*-
"""TODO: doc
"""

__author__ = "Anderson Bravalheri"
__copyright__ = "Copyright (C) 2016 Anderson Bravalheri"
__license__ = "mozilla"

PREFIX_SEPARATOR = ':'

BUILT_IN_TYPES = (
    'binary',
    'bits',
    'boolean',
    'decimal64',
    'empty',
    'enumeration',
    'identityref',
    'instance-identifier',
    'int8',
    'int16',
    'int32',
    'int64',
    'leafref',
    'string',
    'uint8',
    'uint16',
    'uint32',
    'uint64',
    'union',
)

YANG_KEYWORDS = (
    'status',
    'mandatory',
    'reference',
    'presence',
    'when',
    'if-feature',
    'anyxml',
    'argument',
    'module',
    'prefix',
    'refine',
    'path',
    'ordered-by',
    'range',
    'typedef',
    'position',
    'container',
    'output',
    'notification',
    'min-elements',
    'namespace',
    'feature',
    'type',
    'revision-date',
    'units',
    'import',
    'include',
    'config',
    'deviate',
    'revision',
    'deviation',
    'yin-element',
    'require-instance',
    'description',
    'anydata',
    'enum',
    'choice',
    'belongs-to',
    'submodule',
    'error-app-tag',
    'base',
    'uses',
    'key',
    'input',
    'leaf',
    'bit',
    'unique',
    'identity',
    'must',
    'case',
    'yang-version',
    'max-elements',
    'error-message',
    'augment',
    'default',
    'leaf-list',
    'fraction-digits',
    'list',
    'rpc',
    'value',
    'extension',
    'length',
    'contact',
    'pattern',
    'action',
    'organization',
    'modifier',
    'grouping',
)
